Nikhil info
CMU-MS-DAS-Modern-Programming-Mini/ClassAssignmentNo1 pull request #13
Opened 2021-09-14 05:36 UTC by nikhil1007

Pull request created as part of Class Assignment-1

2021-09-17 12:06 UTC, shots47s requested changes
See comments in the file.

2021-09-17 12:06 UTC, shots47s commented on index.html
> -				copy and paste yours
You did not follow the instructions, I asked you to copy the slide to here, please conform to that instruction.

2021-09-17 12:06 UTC, shots47s commented on index.html
> +    <div class="slides">
This is an extraneous change, please restore to the original format.

2021-09-18 04:52 UTC, closed without merging

2021-09-18 04:53 UTC, nikhil1007 commented
I had a lot of errors working with the branch "nikhil_info", I deleted it and have submitted a new pull request.