Hwankyus slide - pull request
CMU-MS-DAS-Modern-Programming-Mini/ClassAssignmentNo1 pull request #20
Opened 2021-09-16 17:39 UTC by hwankyusong

2021-09-17 11:51 UTC, shots47s requested changes
Please see my comments in the file to correct, you have several extraneous statements.

2021-09-17 11:51 UTC, shots47s commented on index.html
> +        hwankyus_slide
Extraneous statement

2021-09-17 11:51 UTC, shots47s commented on index.html
> +        main
Extraneous statement

2021-09-17 11:51 UTC, shots47s commented on index.html
>  			   copy above and fill in
Remove this line.

2021-09-17 11:58 UTC, hwankyusong commented
I believe I've removed all the extraneous statements, as per your comments.

2021-09-21 15:08 UTC, shots47s approved these changes
Looks good.

2021-09-23 19:04 UTC, merged